name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwilhe2/silly-db@main
      id: db
      with:
        key: France
    - run: echo ${{ steps.db.outputs.value }}
