name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwilhe2/silly-db@main
      id: db
      with:
        key: France
    - run: echo ${{ steps.db.outputs.value }}
    - uses: fwilhe2/silly-db@main
      with:
        key: Greece
        query: write
        value: Athens
    - run: ls -la
    - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
